[build]
  publish = "website"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/config"
  to = "/.netlify/functions/config"
  status = 200

[[redirects]]
  from = "/api/checkout"
  to = "/.netlify/functions/checkout"
  status = 200

[[redirects]]
  from = "/api/payment-status/*"
  to = "/.netlify/functions/payment-status?session_id=:splat"
  status = 200

[[redirects]]
  from = "/api/payment-status"
  to = "/.netlify/functions/payment-status"
  status = 200

[[redirects]]
  from = "/api/webhook"
  to = "/.netlify/functions/webhook"
  status = 200
